src/Entity/ProductLine.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductLineRepository")
 */
class ProductLine
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ShoppingCart", inversedBy="ProductLine")
     */
    private $shoppingCart;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", inversedBy="productLines")
     */
    private $Product;

    public function getId()
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getShoppingCart(): ?ShoppingCart
    {
        return $this->shoppingCart;
    }

    public function setShoppingCart(?ShoppingCart $shoppingCart): self
    {
        $this->shoppingCart = $shoppingCart;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->Product;
    }

    public function setProduct(?Product $Product): self
    {
        $this->Product = $Product;

        return $this;
    }
}

src/Entity/ShoppingCart.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ShoppingCartRepository")
 */
class ShoppingCart
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="shoppingCart", cascade={"persist"})
     */
    private $User;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ProductLine", mappedBy="shoppingCart", cascade={"persist", "remove"})
        */
        private $ProductLine;

    public function __construct()
    {
        $this->ProductLine = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection|ProductLine[]
     */
    public function getProductLine(): Collection
    {
        return $this->ProductLine;
    }

    public function addProductLine(ProductLine $productLine): self
    {
        if (!$this->ProductLine->contains($productLine)) {
            $this->ProductLine[] = $productLine;
            $productLine->setShoppingCart($this);
        }

        return $this;
    }

    public function removeProductLine(ProductLine $productLine): self
    {
        if ($this->ProductLine->contains($productLine)) {
            $this->ProductLine->removeElement($productLine);
            // set the owning side to null (unless already changed)
            if ($productLine->getShoppingCart() === $this) {
                $productLine->setShoppingCart(null);
            }
        }

        return $this;
    }
}

src/Controller/ShoppingCartController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Session\Session;
use Doctrine\Common\Persistence\ObjectManager;
use App\Entity\ShoppingCart;

class ShoppingCartController extends Controller
{
    /**
     * @Route("user/shopping/cart", name="shopping_cart")
     */
    public function index(Session $session = null, ObjectManager $manager)
    {
        

            $cart =$this->getUser()->getShoppingCart();
            if(!$cart){
                $cart = new ShoppingCart();
            }

            $totalPrice = 0;
            foreach($cart->getProductLine() as $line) {
                $totalPrice = $totalPrice + $line->getPrice();
            }
            
        

            $cart = $this->getDoctrine()->getManager()->merge($cart);
            $productLine = $cart->getProductLine();

            $manager->persist($cart);
            $manager->flush();
            
        return $this->render('shopping_cart/index.html.twig', [
            "productLine" => $productLine,
            "totalPrice" => $totalPrice
        ]);
    }

}

templates/shopping_cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    <title>
        Panier
    </title>
{% endblock %}

{% block body %}

<div class="container-fluid">
  <div class="col-md-6 mx-auto" id="shopping">
    <h1 class="shopping-cart mb-4">Panier</h1>
        <table class="table" >
          <thead>
            <tr>
              <th>Produit</th>
              <th>Quantité</th>
              <th>Prix</th>
            </tr>
          </thead>
           {% for row in productLine %}
          <tbody>
        
            <tr class="table">
                    <td>{{row.product.name}}</td>
                    <!-- <td>{{row.product.image}}</td> -->
                    <td>{{row.quantity}}</td>
                    <td>{{row.price}}.00€</td>
                    <td><a class="btn" style="color:black;" href="{{ path("remove_productLine", {"id": row.id}) }}"><i class="fas fa-trash-alt"></i></a></td>
            </tr>
         
          </tbody> 
            {% endfor %}
        </table>
      <p class="priceTotal">Prix Total: {{totalPrice}}.00€</p>

      <div  id="command">
        <a href="{{path('remove_productLines')}}" class="btn btn-primary" type="button" data-toggle="modal" data-target="#exampleModalCenter">Finaliser votre commande</a>
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">Votre commande va être expédiée sous peu !</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              </div>
            </div>
          </div>
      </div>

    </div>
  </div>


{% endblock %}